#!/bin/bash

if [[ ! -z "${UCVM_INSTALL_PATH}" ]]; then
  if [[ -d "${UCVM_INSTALL_PATH}/model/cvmhlabn/lib" ]]; then
    env DYLD_LIBRARY_PATH=${UCVM_INSTALL_PATH}/model/cvmsi/lib:${DYLD_LIBRARY_PATH} ./unittest
    exit
  fi
fi

env DYLD_LIBRARY_PATH=../src:${DYLD_LIBRARY_PATH} ./unittest
