name: cvmsi-ucvm-ci

on:
  push:
    branches: [ main ]

jobs:
  cvmsi-build-ucvm-linux:
#   if: ${{ failure() }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - name: set UCVM_SRC_PATH 
      run: echo "UCVM_SRC_PATH=$RUNNER_WORKSPACE/cvmsi/ucvm" >> $GITHUB_ENV
    - name: set UCVM_INSTALL_PATH 
      run: echo "UCVM_INSTALL_PATH=$RUNNER_WORKSPACE/cvmsi/target" >> $GITHUB_ENV
### build ucvm(main) first 
    - name: get-ucvm 
      uses: actions/checkout@v2
      with: 
        repository: 'SCECcode/UCVM'
        ref: testMei
        path: ucvm
    - id: build-ucvm
      name: build ucvm
      uses: ./ucvm/.github/actions/build-ucvm-action
      with:
         initiating-repo: 'cvmsi'
         target-model: 'cvmsi'
    - name: get-result
      run: more ${{ steps.build-ucvm.outputs.build-log }}
      shell: bash
    - name: move stock cvmsi away
      run: (rm -rf $RUNNER_WORKSPACE/cvmsi/ucvm/work/model/cvmsi)
      shell: bash
### build cvmsi from github 
    - name: checkout cvmsi main
      uses: actions/checkout@v2
      with: 
        path: cvmsi
    - name: move it to the right location
      run: (mv cvmsi $RUNNER_WORKSPACE/cvmsi/ucvm/work/model; pwd; ls)
      shell: bash
    - name: build cvmsi as part of ucvm 
      run: (cd $RUNNER_WORKSPACE/cvmsi/ucvm/work/model/cvmsi; ./.github/scripts/cvmsi-build.sh)
      shell: bash
### check ucvm is still valid
    - name: check on ucvm
      run: (source $UCVM_INSTALL_PATH/conf/ucvm_env.sh; ucvm_query -H)
      shell: bash
    - name: test cvmsi with ucvm
      run: (cd $RUNNER_WORKSPACE/cvmsi/ucvm/work/model/cvmsi; source $UCVM_INSTALL_PATH/conf/ucvm_env.sh; ./.github/scripts/cvmsi-test-ucvm.sh)
      shell: bash
    - name: test cvmsi under ucvm
      run: (cd $RUNNER_WORKSPACE/cvmsi/ucvm; source $UCVM_INSTALL_PATH/conf/ucvm_env.sh; ./.github/scripts/ucvm-test.sh)
      shell: bash

##      Test: model_query() points by elevation
## FAIL: assertion 2 != 0
## unmatched result
## /Users/runner/work/cvmsi/cvmsi/ucvm/work/model/cvmsi/test/test_latlons_ucvm_ge.out
## /Users/runner/work/cvmsi/cvmsi/ucvm/work/model/cvmsi/test/./ref/test_latlons_ucvm_ge.ref
## Test: cvmsi_query validate gd option
## FAIL: assertion 1 != 0
## bash-3.2$ diff /Users/runner/work/cvmsi/cvmsi/ucvm/work/model/cvmsi/test/test_latlons_ucvm_ge.out /Users/runner/work/cvmsi/cvmsi/ucvm/work/model/cvmsi/test/./ref/test_latlons_ucvm_ge.ref
## 7c7
## < 1372.415771 2628.551514 2279.880371
## ---
## > 1372.415527 2628.551514 2279.880371
##
  cvmsi-build-ucvm-mac:
    if: ${{ success() }}
    needs: [cvmsi-build-ucvm-linux]
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - name: set UCVM_SRC_PATH 
      run: echo "UCVM_SRC_PATH=$RUNNER_WORKSPACE/cvmsi/ucvm" >> $GITHUB_ENV
    - name: set UCVM_INSTALL_PATH 
      run: echo "UCVM_INSTALL_PATH=$RUNNER_WORKSPACE/cvmsi/target" >> $GITHUB_ENV
### build ucvm(main) first 
    - name: get-ucvm 
      uses: actions/checkout@v2
      with: 
        repository: 'SCECcode/UCVM'
        ref: testMei
        path: ucvm
    - id: build-ucvm
      name: build ucvm
      uses: ./ucvm/.github/actions/build-ucvm-action
      with:
         initiating-repo: 'cvmsi'
         target-model: 'cvmsi'
    - name: get-result
      run: more ${{ steps.build-ucvm.outputs.build-log }}
      shell: bash
    - name: move stock cvmsi away
      run: (rm -rf $RUNNER_WORKSPACE/cvmsi/ucvm/work/model/cvmsi)
      shell: bash
### build cvmsi from github 
    - name: checkout cvmsi main
      uses: actions/checkout@v2
      with: 
        path: cvmsi
    - name: move it to the right location
      run: (mv cvmsi $RUNNER_WORKSPACE/cvmsi/ucvm/work/model; pwd; ls)
      shell: bash
    - name: build cvmsi as part of ucvm 
      run: (cd $RUNNER_WORKSPACE/cvmsi/ucvm/work/model/cvmsi; ./.github/scripts/cvmsi-build.sh)
      shell: bash
### check ucvm is still valid
    - name: check on ucvm
      run: (source $UCVM_INSTALL_PATH/conf/ucvm_env.sh; ucvm_query -H)
      shell: bash
    - name: test cvmsi with ucvm
      run: (cd $RUNNER_WORKSPACE/cvmsi/ucvm/work/model/cvmsi; source $UCVM_INSTALL_PATH/conf/ucvm_env.sh; ./.github/scripts/cvmsi-test-ucvm.sh)
      shell: bash
#   - name: Start SSH debug with tmate
#     if: ${{ failure() }}
#     uses: mxschmitt/action-tmate@v3
#     with:
#       limit-access-to-actor: true
#   - name: sleep to keep runner alive
#     run: sleep 3600
    - name: test cvmsi under ucvm
      run: (cd $RUNNER_WORKSPACE/cvmsi/ucvm; source $UCVM_INSTALL_PATH/conf/ucvm_env.sh; ./.github/scripts/ucvm-test.sh)
      shell: bash




