name: cvmsi-ucvm-ci

on:
  push:
    branches: [ main ]

jobs:
  cvmsi-build-ucvm-mac:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - name: set UCVM_SRC_PATH 
      run: echo "UCVM_SRC_PATH=$RUNNER_WORKSPACE/cvmsi/ucvm" >> $GITHUB_ENV
    - name: set UCVM_INSTALL_PATH 
      run: echo "UCVM_INSTALL_PATH=$RUNNER_WORKSPACE/cvmsi/target" >> $GITHUB_ENV
### build ucvm(main) first 
    - id: get-ucvm 
      uses: actions/checkout@v2
      with: 
        repository: 'SCECcode/UCVM'
        ref: main
        path: ucvm
    - id: look-around
      run: ( echo " cvmsi-ucvm-ci:pwd =>";pwd;
             echo " cvmsi-ucvm-ci:UCVM_SRC_PATH =>"$UCVM_SRC_PATH;
             echo " cvmsi-ucvm-ci:UCVM_INSTALL_PATH =>"$UCVM_INSTALL_PATH;
             echo " cvmsi-ucvm-ci:RUNNER_WORKSPACE =>"$RUNNER_WORKSPACE;
             echo " cvmsi-ucvm-ci:github.action_path =>"${{ github.action_path }};)
      shell: bash
    - id: build-ucvm
      uses: ./ucvm/.github/actions/build-ucvm-action
      with:
         initiating-repo: 'cvmsi'
         target-model: 'cvmsi'
    - id: get-result
      run: more ${{ steps.build-ucvm.outputs.build-log }}
      shell: bash
    - name: move stock cvmsi away
      run: (rm -rf $RUNNER_WORKSPACE/cvmsi/ucvm/work/model/cvmsi)
      shell: bash
### build cvmsi from github 
    - name: checkout cvmsi main
      uses: actions/checkout@v2
      with: 
        ref: main
        path: cvmsi
    - name: move it to the right location
      run: (mv cvmsi $RUNNER_WORKSPACE/cvmsi/ucvm/work/model; pwd; ls)
      shell: bash
    - name: build cvmsi as part of ucvm 
      run: (cd $RUNNER_WORKSPACE/cvmsi/ucvm/work/model/cvmsi; ./.github/scripts/cvmsi-build.sh)
      shell: bash
### check ucvm is still valid
    - name: check on ucvm
      run: (source $UCVM_INSTALL_PATH/conf/ucvm_env.sh; ucvm_query -H)
      shell: bash
    - name: test cvmsi with ucvm
      run: (cd $RUNNER_WORKSPACE/cvmsi/ucvm/work/model/cvmsi; source $UCVM_INSTALL_PATH/conf/ucvm_env.sh; ./.github/scripts/cvmsi-test-ucvm.sh)
      shell: bash
#    - name: Start SSH via Ngrok
#      if: ${{ success() }}
#      uses: luchihoratiu/debug-via-ssh@main
#      with:
#            NGROK_AUTH_TOKEN: ${{ secrets.NGROK_TOKEN }}
#            NGROK_TIMEOUT: 3000
#            SSH_PASS: ${{ secrets.NGROK_SECRET }}
    - name: test cvmsi under ucvm
      run: (cd $RUNNER_WORKSPACE/cvmsi/ucvm; source $UCVM_INSTALL_PATH/conf/ucvm_env.sh; ./.github/scripts/ucvm-test.sh)
      shell: bash

  cvmsi-build-ucvm-linux:
#    runs-on: ubuntu-latest
#      not working:       gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1)
# 
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - name: set UCVM_SRC_PATH 
      run: echo "UCVM_SRC_PATH=$RUNNER_WORKSPACE/cvmsi/ucvm" >> $GITHUB_ENV
    - name: set UCVM_INSTALL_PATH 
      run: echo "UCVM_INSTALL_PATH=$RUNNER_WORKSPACE/cvmsi/target" >> $GITHUB_ENV
### build ucvm(main) first 
    - id: get-ucvm 
      uses: actions/checkout@v2
      with: 
        repository: 'SCECcode/UCVM'
        ref: main
        path: ucvm
    - id: build-ucvm
      uses: ./ucvm/.github/actions/build-ucvm-action
      with:
         initiating-repo: 'cvmsi'
         target-model: 'cvmsi'
    - name: Start SSH via Ngrok
      if: ${{ success() }}
      uses: luchihoratiu/debug-via-ssh@main
      with:
            NGROK_AUTH_TOKEN: ${{ secrets.NGROK_TOKEN }}
            NGROK_TIMEOUT: 3000
            SSH_PASS: ${{ secrets.NGROK_SECRET }}
    - id: get-result
      run: more ${{ steps.build-ucvm.outputs.build-log }}
      shell: bash
    - name: move stock cvmsi away
      run: (rm -rf $RUNNER_WORKSPACE/cvmsi/ucvm/work/model/cvmsi)
      shell: bash
### build cvmsi from github 
    - name: checkout cvmsi main
      uses: actions/checkout@v2
      with: 
        path: cvmsi
    - name: move it to the right location
      run: (mv cvmsi $RUNNER_WORKSPACE/cvmsi/ucvm/work/model; pwd; ls)
      shell: bash
    - name: build cvmsi as part of ucvm 
      run: (cd $RUNNER_WORKSPACE/cvmsi/ucvm/work/model/cvmsi; ./.github/scripts/cvmsi-build.sh)
      shell: bash
### check ucvm is still valid
    - name: check on ucvm
      run: (source $UCVM_INSTALL_PATH/conf/ucvm_env.sh; ucvm_query -H)
      shell: bash
    - name: test cvmsi with ucvm
      run: (cd $RUNNER_WORKSPACE/cvmsi/ucvm/work/model/cvmsi; source $UCVM_INSTALL_PATH/conf/ucvm_env.sh; ./.github/scripts/cvmsi-test-ucvm.sh)
      shell: bash
#    - name: Start SSH via Ngrok
#      if: ${{ success() }}
#      uses: luchihoratiu/debug-via-ssh@main
#      with:
#            NGROK_AUTH_TOKEN: ${{ secrets.NGROK_TOKEN }}
#            NGROK_TIMEOUT: 3000
#            SSH_PASS: ${{ secrets.NGROK_SECRET }}
    - name: test cvmsi under ucvm
      run: (cd $RUNNER_WORKSPACE/cvmsi/ucvm; source $UCVM_INSTALL_PATH/conf/ucvm_env.sh; ./.github/scripts/ucvm-test.sh)
      shell: bash



